### ISSUE TITLE
Uncaught ReflectionException: Class path.storage does not exist in

### ISSUE THREAD

**Issue by ihsanberahim** [nasrulhazim/lumen-in-laravel#1]
I pointed api-myapi.dev to `laravel/lumen/public`;

After i enabled
`$app->withEloquent();`
in 
`laravel/lumen/bootstrap.php`

I got error

```
Fatal error: Uncaught ReflectionException: Class path.storage does not exist in /Users/Developer/Sites/LaravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php:681 Stack trace:
 #0 /Users/Developer/Sites/LaravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): ReflectionClass->__construct('path.storage')
 #1 /Users/Developer/Sites/LaravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php(565): Illuminate\Container\Container->build('path.storage')
 #2 /Users/Developer/Sites/LaravelProject/vendor/laravel/lumen-framework/src/Application.php(208): Illuminate\Container\Container->make('path.storage')
 #3 /Users/Developer/Sites/LaravelProject/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(105): Laravel\Lumen\Application->make('path.storage')
 #4 /Users/Developer/Sites/LaravelProject/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(800): app('path.storage')
 #5 /Users/Developer/Sites/LaravelProject/config/view.php(31): storage_path('framework in /Users/Developer/Sites/LaravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 681
```

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ReflectionException: Class path.storage does not exist in /Users/Developer/Sites/LaravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php:681 Stack trace:
 #0 /Users/Developer/Sites/LaravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): ReflectionClass->__construct('path.storage')
 #1 /Users/Developer/Sites/LaravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php(565): Illuminate\Container\Container->build('path.storage')
 #2 /Users/Developer/Sites/LaravelProject/vendor/laravel/lumen-framework/src/Application.php(208): Illuminate\Container\Container->make('path.storage')
 #3 /Users/Developer/Sites/LaravelProject/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(105): Laravel\Lumen\Application->make('path.storage')
 #4 /Users/Developer/Sites/LaravelProject/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(800): app('path.storage')
 #5 /Users/Developer in /Users/Developer/Sites/LaravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 681
```

I have no idea so far. Thank you for your advices.

**Comment by ihsanberahim** [comment]
```
$app = new Laravel\Lumen\Application(
    realpath(__DIR__.'/../')
);

$app->instance('path.storage', app()->basePath() . DIRECTORY_SEPARATOR . 'storage');

$app->withFacades();

$app->withEloquent();
```

I found a working [solution](https://github.com/laravel/lumen-framework/issues/504).

**Comment by nasrulhazim** [comment]
hahaha, @ihsanberahim ..self-resolved nampaknya. hahah..

**Comment by gurpalsingh1919** [comment]
looking same issue in laravel 5.4
